### PR TITLE
added explanation

### PR DESCRIPTION
**Pull request by nathmo**
added a few explanation
added the rapsberry pi install procedure
added image creation and publication

### CODE REVIEW

**Comment by kuklinistvan** [comment]
Hello,

I'm looking at the PR right now. I really appreciate your contribution but I think we still have some pieces that require some tidying. Although I see your intention, I think we can agree on that this does not look that good:

image

image

image

* We need some restructuring, yes, but...
  * This is a repository for a Docker image that provides an easy way to set up an Anki server, and that's it. Its README should contain everything that is specific to this scenario and maybe a little bit of guidance. At the moment - before your contribution - I already feel that it is starting trying to do too much (which is where I fail to allocate time for it to clean it up).
  * I would like to follow the UNIX philosophy - I do not think that this repository is the place for teaching everyone Linux and Docker.  Although I'm okay with creating a Docker tutorial for complete beginners, I don't think that it belongs to this repository, or at least to this README. I would like it better if we had a README that assumes that one has the basic skills related to Docker usage (as most other repositories do), and maybe we can create another one that explains things in a more verbose way - a `Walkthrough_for_beginners.md`. We could link that from the main README.
    * (though, for a walk through, maybe a video could be more suitable, but it is only a question of detail)
    * Also, it would be kind of interesting to see every repository that provides a Docker image teaching all the basics every time, but if there is a demand for that in our case, go ahead - I just don't think that it is a good idea to mix everything together in one README.
* In a `README.md`, please begin the titles and the sentences with uppercase letter and use punctuations. Also, please use the spell checker. It just looks very unprofessional to have typos all over the place. From my experience, if I see one or two typos in the first three seconds when I visit a repository, I close it and never look back.

Although I see where this description needs more work, and once again, I really appreciate that you put the time in it, I still would like to see a tendency to a cleaner repository. As a rule of thumb, I would agree on that every PR should make the repository a bit cleaner than it was before, but at least keep the shape (also known as [The Boy Scout Rule](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)).

@VikashKothary, @AntonOfTheWoods, I am interested in your opinion on this problem above. Please state if you don't (completely) agree with me.

**Comment by VikashKothary** [comment]
Hi @nathmo,

This looks like some good stuff. I'm always a fan of documentation so this is much appricated. 

I agree this PR still needs a bit of work but imo this is mainly because it's a bit too busy. If you break down your PR, I see things moving quicker as we can merge the bits that are perfect and discuss the points that still need changes.

Here's what I see as separate features and therefore separate PRs:
- Minor changes to header
- Descriptions in the News section. (Good idea btw)
- General Usage Preamble
- One-time setup Preamble
- Deploying on a Raspberry Pi
- Creating a docker image on a new Device (Controversial one but defo worth discussing)
- Creating users
- HTTPS Encryption with Apache Proxy

Now that might seem like a lot of PRs but I think it speaks to the amount of work you've done :P

One note for all is a README should be a place to provide a completely non-technical overview for a project. This is because a README should not frighten off beginners. So there's definitely a need for a `docs` folder in the future to contain a lot of this technical documentation. But that's a problem for tomorrow 👍 

Great job again.

**Comment by kuklinistvan** [comment]
> One note for all is a README should be a place to provide a completely non-technical overview for a project. This is because a README should not frighten off beginners. So there's definitely a need for a docs folder in the future to contain a lot of this technical documentation

I absolutely support this ;)

**Comment by nathmo** [comment]
Hi, thanks for the feed back i will take into account the suggestions you gave. Maybe see to split it in two or three file.
(Sorry for the spellings mistakes i will spend some time reviewing them ) maybe it would make more sense to commit a few explanation the the Anki sync server repo as it more general and just usea  reference to there

**Comment by kuklinistvan** [comment]
Anki Community needs a wiki, I think :))

What's up with this site anyway?

https://ankicommunity.github.io/

**Comment by nathmo** [comment]
A wiki would probably be the best way of going. shall i try to fork https://ankicommunity.github.io/ and making my PR there ?

**Comment by kuklinistvan** [comment]
I think we need a separate ticket for that, because that would be a bigger project. If we are to populate that page, It would be great if it point to our Gitter channel, have some rudimentary news feed, and of course, would have a tutorial section.


Are you familiar with MKDocs? It has a gorgeous Material Design theme with an awesome search module and it is almost ridiculous how easy it is to use.
Guys, check it out, we can easily host it from Github Pages.

https://squidfunk.github.io/mkdocs-material/getting-started/
https://www.mkdocs.org/user-guide/deploying-your-docs/

**Comment by kuklinistvan** [comment]
Continue the discussion on the Wiki here: https://github.com/ankicommunity/ankicommunity.github.io/issues/1

**Comment by kuklinistvan** [comment]
Hey @nathmo, the Anki community wiki is up.

I would like to clean up the README of this repository and place a link at the top to the detailed walk-through on the wiki. Would you like to port your work there?

**Comment by nathmo** [comment]
Indeed, i will commit there. Thanks ^^

**Pull request closed without merging**
